// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.35.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class DatabaseInfo {
  final String name;
  final String address;
  final String port;
  final String username;
  final String password;
  final String database;

  const DatabaseInfo({
    required this.name,
    required this.address,
    required this.port,
    required this.username,
    required this.password,
    required this.database,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      address.hashCode ^
      port.hashCode ^
      username.hashCode ^
      password.hashCode ^
      database.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DatabaseInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          address == other.address &&
          port == other.port &&
          username == other.username &&
          password == other.password &&
          database == other.database;
}

class TableInfo {
  final String tableName;
  final String columnName;
  final String dataType;

  const TableInfo({
    required this.tableName,
    required this.columnName,
    required this.dataType,
  });

  @override
  int get hashCode =>
      tableName.hashCode ^ columnName.hashCode ^ dataType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TableInfo &&
          runtimeType == other.runtimeType &&
          tableName == other.tableName &&
          columnName == other.columnName &&
          dataType == other.dataType;
}
