// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.35.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TemplateResult {
  final String prompt;
  final int index;
  final String response;

  const TemplateResult({
    required this.prompt,
    required this.index,
    required this.response,
  });

  @override
  int get hashCode => prompt.hashCode ^ index.hashCode ^ response.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TemplateResult &&
          runtimeType == other.runtimeType &&
          prompt == other.prompt &&
          index == other.index &&
          response == other.response;
}

enum TemplateRunningStage {
  format,
  eval,
  optimize,
  done,
  ;
}
