// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.35.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum ErrorModule {
  template,
  llmChat,
  monitors,
  ;
}

enum ErrorType {
  recoverable,
  unrecoverable,
  ;
}

class RustError {
  final ErrorModule module;
  final ErrorType type;
  final String errmsg;
  final String? context;

  const RustError({
    required this.module,
    required this.type,
    required this.errmsg,
    this.context,
  });

  @override
  int get hashCode =>
      module.hashCode ^ type.hashCode ^ errmsg.hashCode ^ context.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustError &&
          runtimeType == other.runtimeType &&
          module == other.module &&
          type == other.type &&
          errmsg == other.errmsg &&
          context == other.context;
}
