// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.31.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class EnvParams {
  final String base;
  final String name;
  final String chatBase;
  final String? sk;

  const EnvParams({
    required this.base,
    required this.name,
    required this.chatBase,
    this.sk,
  });

  @override
  int get hashCode =>
      base.hashCode ^ name.hashCode ^ chatBase.hashCode ^ sk.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnvParams &&
          runtimeType == other.runtimeType &&
          base == other.base &&
          name == other.name &&
          chatBase == other.chatBase &&
          sk == other.sk;
}
