name: langchain_lib
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  langchain: ^0.7.1
  langchain_openai: ^0.6.1+1


dev_dependencies:
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0

flutter:

