// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.35.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Software {
  final String name;
  final String iconPath;
  final Uint8List? icon;

  const Software({
    required this.name,
    required this.iconPath,
    this.icon,
  });

  @override
  int get hashCode => name.hashCode ^ iconPath.hashCode ^ icon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Software &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          iconPath == other.iconPath &&
          icon == other.icon;
}
