// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.31.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../llm.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void initLlm({String? p, dynamic hint}) =>
    RustLib.instance.api.initLlm(p: p, hint: hint);

EnvParams? getLlmConfig({dynamic hint}) =>
    RustLib.instance.api.getLlmConfig(hint: hint);

Stream<LLMMessage> llmMessageStream({dynamic hint}) =>
    RustLib.instance.api.llmMessageStream(hint: hint);

Future<void> chat(
        {String? uuid,
        List<LLMMessage>? history,
        required bool stream,
        required String query,
        dynamic hint}) =>
    RustLib.instance.api.chat(
        uuid: uuid, history: history, stream: stream, query: query, hint: hint);
