// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.31.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../errors.dart';
import '../frb_generated.dart';
import '../llm.dart';
import '../llm/app_flowy_model.dart';
import '../llm/template.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void initLlm({required String p, dynamic hint}) =>
    RustLib.instance.api.initLlm(p: p, hint: hint);

EnvParams? getLlmConfig({dynamic hint}) =>
    RustLib.instance.api.getLlmConfig(hint: hint);

Stream<LLMMessage> llmMessageStream({dynamic hint}) =>
    RustLib.instance.api.llmMessageStream(hint: hint);

Stream<String> aiHelperMessageStream({dynamic hint}) =>
    RustLib.instance.api.aiHelperMessageStream(hint: hint);

Stream<TemplateResult> templateMessageStream({dynamic hint}) =>
    RustLib.instance.api.templateMessageStream(hint: hint);

Stream<RustError> errorMessageStream({dynamic hint}) =>
    RustLib.instance.api.errorMessageStream(hint: hint);

Stream<TemplateRunningStage> templateStateStream({dynamic hint}) =>
    RustLib.instance.api.templateStateStream(hint: hint);

Future<void> chat(
        {String? uuid,
        List<LLMMessage>? history,
        required bool stream,
        required String query,
        dynamic hint}) =>
    RustLib.instance.api.chat(
        uuid: uuid, history: history, stream: stream, query: query, hint: hint);

Future<void> sequentialChainChat(
        {required String jsonStr, required String query, dynamic hint}) =>
    RustLib.instance.api
        .sequentialChainChat(jsonStr: jsonStr, query: query, hint: hint);

Future<String?> templateRenderer({required String template, dynamic hint}) =>
    RustLib.instance.api.templateRenderer(template: template, hint: hint);

Future<List<(String, AttributeType, String?)>> templateToPrompts(
        {required String template, dynamic hint}) =>
    RustLib.instance.api.templateToPrompts(template: template, hint: hint);

Future<void> generateFromTemplate(
        {required List<(String, int, int?, AttributeType, String?)> v,
        required bool enablePlugin,
        dynamic hint}) =>
    RustLib.instance.api
        .generateFromTemplate(v: v, enablePlugin: enablePlugin, hint: hint);

Future<String> optimizeDoc({required String s, dynamic hint}) =>
    RustLib.instance.api.optimizeDoc(s: s, hint: hint);

Root? getDocRootFromStr({required String s, dynamic hint}) =>
    RustLib.instance.api.getDocRootFromStr(s: s, hint: hint);

Future<void> aiHelperQuickRequest(
        {required String s,
        required String tone,
        required String lang,
        required String length,
        required List<String> extra,
        dynamic hint}) =>
    RustLib.instance.api.aiHelperQuickRequest(
        s: s, tone: tone, lang: lang, length: length, extra: extra, hint: hint);

Future<void> initPromptFromPath({required String s, dynamic hint}) =>
    RustLib.instance.api.initPromptFromPath(s: s, hint: hint);
