// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.35.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../software_monitor/software.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initMonitor({required List<(int, String)> items, dynamic hint}) =>
    RustLib.instance.api
        .crateApiSoftwareMonitorApiInitMonitor(items: items, hint: hint);

Future<List<Software>> getInstalledSoftwares({dynamic hint}) =>
    RustLib.instance.api
        .crateApiSoftwareMonitorApiGetInstalledSoftwares(hint: hint);

Stream<Int64List> softwareWatchingMessageStream({dynamic hint}) =>
    RustLib.instance.api
        .crateApiSoftwareMonitorApiSoftwareWatchingMessageStream(hint: hint);

Stream<(Int64List, String)> softwareWatchingWithForegroundMessageStream(
        {dynamic hint}) =>
    RustLib.instance.api
        .crateApiSoftwareMonitorApiSoftwareWatchingWithForegroundMessageStream(
            hint: hint);

Future<void> addToWatchingList(
        {required int id, required String name, dynamic hint}) =>
    RustLib.instance.api.crateApiSoftwareMonitorApiAddToWatchingList(
        id: id, name: name, hint: hint);

Future<void> removeFromWatchingList({required int id, dynamic hint}) =>
    RustLib.instance.api
        .crateApiSoftwareMonitorApiRemoveFromWatchingList(id: id, hint: hint);
