// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.31.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// The type `_PinWindowItem` is not used by any `pub` functions, thus it is ignored.

Future<void> createEventLoop({dynamic hint}) =>
    RustLib.instance.api.createEventLoop(hint: hint);

Future<void> showTodos(
        {required List<RustSimpleNotifyLibPinWindowItem> data, dynamic hint}) =>
    RustLib.instance.api.showTodos(data: data, hint: hint);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::rust_async::RwLock<rust_simple_notify_lib :: PinWindowItem>>
@sealed
class RustSimpleNotifyLibPinWindowItem extends RustOpaque {
  RustSimpleNotifyLibPinWindowItem.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  RustSimpleNotifyLibPinWindowItem.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib.instance.api
        .rust_arc_increment_strong_count_RustSimpleNotifyLibPinWindowItem,
    rustArcDecrementStrongCount: RustLib.instance.api
        .rust_arc_decrement_strong_count_RustSimpleNotifyLibPinWindowItem,
    rustArcDecrementStrongCountPtr: RustLib.instance.api
        .rust_arc_decrement_strong_count_RustSimpleNotifyLibPinWindowItemPtr,
  );
}
